name: lryc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0+1
  path_provider: ^2.1.4
  syncfusion_flutter_pdf: ^26.2.14
  shared_preferences: ^2.3.2
  http: ^1.2.2
  pdfx: ^2.9.1
  sqflite: ^2.2.8
  path: ^1.8.0
  provider: ^6.1.2  # ← AGREGAR ESTA LÍNEA
  local_auth: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icono_urp.png"
